basePath: /v2
definitions:
  model.AddFavouritePayload:
    properties:
      MotelCode:
        type: string
    type: object
  model.ChangePassPayload:
    properties:
      NewPass:
        example: abc@124
        type: string
      OldPass:
        example: abc@123
        type: string
    type: object
  model.CreateMotelPayload:
    properties:
      Address:
        example: Ngõ 2, Phạm Văn Đồng, Cầu Giấy, Hà Nội
        type: string
      Cost:
        example: 3.3
        type: number
      Description:
        example: Nhà rộng rãi, thoáng mát
        type: string
      Image:
        example: https://file4.batdongsan.com.vn/2020/08/28/20200828202318-987e_wm.jpg
        type: string
      Images:
        example:
        - https://file4.batdongsan.com.vn/2020/08/28/20200828202318-987e_wm.jpg
        items:
          type: string
        type: array
      Latitude:
        example: "21.0286755"
        type: string
      Longitude:
        example: 105.7558943,13z
        type: string
      Tags:
        example:
        - hanoi
        items:
          type: string
        type: array
      Title:
        example: CCMN SỐ 1A NGÕ 49 TRIỀU KHÚC, FULL HẾT ĐỒ THANG MÁY BAN CÔNG, BẾP TÁCH RIÊNG, 26M2 GIÁ TỪ 3,3 TR/TH
        type: string
    type: object
  model.CreateUserPayload:
    properties:
      FullName:
        example: Kiều Chí Công
        type: string
      PassWord:
        example: abc123
        type: string
      RoleCode:
        example: ADMIN
        type: string
      UserName:
        example: kieuchicong
        type: string
    type: object
  model.GetManyResponse:
    properties:
      Data:
        items:
          type: object
        type: array
      Error:
        type: string
      Message:
        type: string
    type: object
  model.GetOneResponse:
    properties:
      Data:
        type: object
      Error:
        type: string
      Message:
        type: string
    type: object
  model.LoginPayload:
    properties:
      PassWord:
        example: abc123
        type: string
      UserName:
        example: kieuchicong
        type: string
    type: object
  model.UpdateMotelPayload:
    properties:
      Address:
        example: Ngõ 2, Phạm Văn Đồng, Cầu Giấy, Hà Nội
        type: string
      Cost:
        example: 3.3
        type: number
      Description:
        example: Nhà rộng rãi, thoáng mát
        type: string
      FinishedAt:
        example: "2021-01-15T22:20:28.227+00:00"
        type: string
      Image:
        example: https://file4.batdongsan.com.vn/2020/08/28/20200828202318-987e_wm.jpg
        type: string
      Images:
        example:
        - https://file4.batdongsan.com.vn/2020/08/28/20200828202318-987e_wm.jpg
        items:
          type: string
        type: array
      Latitude:
        example: "21.0286755"
        type: string
      Longitude:
        example: 105.7558943,13z
        type: string
      Status:
        example: true
        type: boolean
      Tags:
        example:
        - hanoi
        items:
          type: string
        type: array
      Title:
        example: CCMN SỐ 1A NGÕ 49 TRIỀU KHÚC, FULL HẾT ĐỒ THANG MÁY BAN CÔNG, BẾP TÁCH RIÊNG, 26M2 GIÁ TỪ 3,3 TR/TH
        type: string
    type: object
  model.UpdateUserInfoPayload:
    properties:
      Email:
        example: example@gmail.com
        type: string
      FullName:
        example: Kiều Chí Công
        type: string
      Phone:
        example: "0795048768"
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /motel:
    get:
      description: GetMotelsByFilter
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetManyResponse'
      security:
      - ApiKeyAuth: []
      summary: Lấy danh sách bài đăng
      tags:
      - Motel
    post:
      description: CreateMotel
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateMotelPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      summary: Tạo bài đăng
      tags:
      - Motel
  /motel/{code}:
    get:
      description: GetMotelByCode
      parameters:
      - description: Motel code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      summary: Lấy bài đăng theo code
      tags:
      - Motel
    patch:
      description: CreateMotel
      parameters:
      - description: Motel code
        in: path
        name: code
        required: true
        type: string
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateMotelPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      summary: Cập nhật bài đăng
      tags:
      - Motel
  /user:
    get:
      description: GetUsersByFilter
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetManyResponse'
      security:
      - ApiKeyAuth: []
      summary: Lấy danh sách Tài khoản
      tags:
      - User
    post:
      description: CreateUser
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      summary: Tạo tài khoản
      tags:
      - User
  /user/{code}:
    get:
      description: GetUserByCode
      parameters:
      - description: User code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      summary: Lấy Thông tin User theo code
      tags:
      - User
  /user/add-favourite-motel:
    post:
      description: AddMotelFavourites
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddFavouritePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      security:
      - ApiKeyAuth: []
      summary: Thêm bài đăng yêu thích
      tags:
      - User
  /user/change-pass:
    patch:
      description: ChangePass
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangePassPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      security:
      - ApiKeyAuth: []
      summary: Đổi mật khẩu tài khoản
      tags:
      - User
  /user/info:
    patch:
      description: UpdateUser
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserInfoPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      security:
      - ApiKeyAuth: []
      summary: Cập nhật Thông tin tài khoản
      tags:
      - User
  /user/login:
    post:
      description: LoginUser
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      summary: Đăng nhập tài khoản
      tags:
      - User
  /user/remove-favourite-motel:
    post:
      description: RemoveMotelFavourites
      parameters:
      - description: request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddFavouritePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetOneResponse'
      security:
      - ApiKeyAuth: []
      summary: Bỏ bài đăng yêu thích
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
